import picomatch from 'picomatch';

/**
 * How specific is a pattern?
 *
 * We rank by the length of the literal text before the first wildcard, then by
 * total pattern length. That gives us a score that does not depend on what
 * order the patterns were written in.
 *
 * Why order-independence matters: the plan file is meant to be generated by a
 * planning agent, so the order of the patterns is basically random. If order
 * decided who wins, the same plan could mean two different things.
 *
 * This is on purpose DIFFERENT from GitHub CODEOWNERS, where the last matching
 * line wins. Say so loudly in the docs.
 */
export function specificity(pattern) {
  const firstWildcard = pattern.search(/[*?[{]/);
  const literalPrefix = firstWildcard === -1 ? pattern.length : firstWildcard;
  return { literalPrefix, total: pattern.length };
}

export function compare(a, b) {
  if (a.literalPrefix !== b.literalPrefix) return b.literalPrefix - a.literalPrefix;
  return b.total - a.total;
}

const matcherCache = new Map();

function matcher(pattern) {
  let m = matcherCache.get(pattern);
  if (!m) {
    m = picomatch(pattern, { dot: true });
    matcherCache.set(pattern, m);
  }
  return m;
}

export function matches(pattern, filePath) {
  return matcher(pattern)(filePath);
}

/**
 * Build a lookup table from the plan's units.
 * Returns [{ pattern, unitId, score }] sorted most specific first.
 */
export function buildOwnership(plan) {
  const claims = [];
  for (const unit of plan.units) {
    for (const pattern of unit.owns) {
      claims.push({ pattern, unitId: unit.id, score: specificity(pattern) });
    }
  }
  claims.sort((a, b) => compare(a.score, b.score));
  return claims;
}

/**
 * Which unit owns this file? Returns null when nobody claims it.
 */
export function resolveOwner(claims, filePath) {
  for (const claim of claims) {
    if (matches(claim.pattern, filePath)) {
      return { unitId: claim.unitId, pattern: claim.pattern };
    }
  }
  return null;
}

/**
 * Is this file frozen? Frozen always beats ownership.
 */
export function resolveFrozen(plan, filePath) {
  const hits = plan.frozen
    .filter((f) => matches(f.path, filePath))
    .sort((a, b) => compare(specificity(a.path), specificity(b.path)));
  return hits[0] ?? null;
}

/**
 * Do two patterns overlap? Used before any agent runs, to catch two units
 * claiming the same ground.
 *
 * There is no exact way to intersect two globs without a lot of machinery, so
 * we test each pattern against a set of concrete paths derived from the other.
 * This catches every realistic case and never reports a false overlap.
 */
export function patternsOverlap(a, b) {
  if (a === b) return true;
  for (const probe of probesFor(a)) {
    if (matches(b, probe)) return true;
  }
  for (const probe of probesFor(b)) {
    if (matches(a, probe)) return true;
  }
  return false;
}

/**
 * Turn a pattern into a few concrete example paths it would match.
 */
function probesFor(pattern) {
  const probes = new Set();
  const fillers = ['x', 'x/y', 'x/y/z'];

  if (!/[*?[{]/.test(pattern)) {
    probes.add(pattern);
    return [...probes];
  }

  for (const filler of fillers) {
    let p = pattern
      .replace(/\*\*\/?/g, `${filler}/`)
      .replace(/\*/g, 'x')
      .replace(/\?/g, 'x')
      .replace(/\[[^\]]*\]/g, 'x')
      .replace(/\{([^,}]*)[^}]*\}/g, '$1');
    p = p.replace(/\/+/g, '/').replace(/\/$/, '');
    if (p) probes.add(p);
  }
  return [...probes];
}
